import { MapView } from "@/components/Map";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, ArrowUpRight, CarFront, CheckCircle2, ChevronRight, CloudSun, Flame, Gauge, History, LayoutDashboard, MapPin, Menu, ShieldAlert, Thermometer, Users, Wind, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

const riskTone: Record<string, string> = { green: "bg-[#dff5e7] text-[#16713b] border-[#b5e4c4]", yellow: "bg-[#fff3c4] text-[#876200] border-[#f1d36f]", red: "bg-[#ffe1df] text-[#b82926] border-[#f2aaa6]" };
const riskDot: Record<string, string> = { green: "bg-[#23a455]", yellow: "bg-[#e1ad10]", red: "bg-[#df3d38]" };

function MetricCard({ label, value, suffix, icon: Icon, detail, tone = "neutral" }: { label: string; value: string | number; suffix?: string; icon: typeof Activity; detail: string; tone?: "neutral" | "green" | "yellow" | "red" }) {
  return <Card className="border-0 bg-white shadow-[0_12px_36px_rgba(31,48,42,.06)]"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#80918b]">{label}</p><p className="mt-3 font-display text-3xl font-semibold tracking-tight text-[#17322b]">{value}<span className="ml-1 text-sm font-medium text-[#80918b]">{suffix}</span></p></div><div className={cn("rounded-2xl p-3", tone === "red" ? "bg-[#fff0ee] text-[#d5443e]" : tone === "yellow" ? "bg-[#fff6d9] text-[#bf8f08]" : tone === "green" ? "bg-[#e5f8eb] text-[#22924b]" : "bg-[#edf4f1] text-[#4d7669]")}><Icon className="h-5 w-5" /></div></div><p className="mt-3 text-xs text-[#74867e]">{detail}</p></CardContent></Card>;
}

function RiskBadge({ level }: { level: string }) { return <span className={cn("inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-bold uppercase tracking-wider", riskTone[level] ?? riskTone.green)}><span className={cn("h-1.5 w-1.5 rounded-full", riskDot[level] ?? riskDot.green)} />{level}</span>; }

export default function Home() {
  const guestMode = true;
  const { data: overview } = trpc.dashboard.overview.useQuery();
  const { data: history = [], refetch } = trpc.scenarios.list.useQuery();
  const [compareIds, setCompareIds] = useState<number[]>([]);
  const { data: comparison = [] } = trpc.scenarios.compare.useQuery({ ids: compareIds }, { enabled: guestMode && compareIds.length > 0 });
  const simulate = trpc.scenarios.simulateAndSave.useMutation({ onSuccess: () => refetch() });
  const [active, setActive] = useState("Overview");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [attendance, setAttendance] = useState([72000]);
  const [startTime, setStartTime] = useState("18:00");
  const [weather, setWeather] = useState<"Hot & humid" | "Warm and clear" | "Storm watch" | "Mild evening">("Hot & humid");
  const [temperature, setTemperature] = useState([94]);
  const [humidity, setHumidity] = useState([72]);
  const [selectedMap, setSelectedMap] = useState<google.maps.Map | null>(null);
  const [lastOutcome, setLastOutcome] = useState<{ crowdDensity: number; heatIndex: number; trafficCongestion: number; riskLevel: string; heatRisk: string; trafficRisk: string; crowdRisk: string; carbonSavedTons: number; minutesSaved: number; recommendations: string[] } | null>(null);

  const fallback = { crowdDensity: 74, heatIndex: 101, trafficCongestion: 81, riskLevel: "red", heatRisk: "red", trafficRisk: "red", crowdRisk: "yellow" };
  const metrics = lastOutcome ?? fallback;
  const recommendationList = lastOutcome?.recommendations ?? ["Reserve a dedicated EV shuttle lane on Main Street and stagger arrivals by gate.", "Deploy mist-cooling stations along the south plaza and transit walk-up corridor.", "Open overflow queuing zones and staff the pedestrian crossing at Kirby Drive."];

  useEffect(() => {
    if (!selectedMap || !overview) return;
    const traffic = new google.maps.TrafficLayer(); traffic.setMap(selectedMap);
    const overlays = overview.hotspots.map((spot) => {
      const color = spot.level === "red" ? "#df3d38" : "#e1ad10";
      return new google.maps.Circle({ map: selectedMap, center: { lat: spot.lat, lng: spot.lng }, radius: spot.level === "red" ? 380 : 270, fillColor: color, fillOpacity: .22, strokeColor: color, strokeOpacity: .75, strokeWeight: 2 });
    });
    const flow = new google.maps.Polyline({ map: selectedMap, path: [{ lat: 29.676, lng: -95.414 }, { lat: 29.6847, lng: -95.4107 }, { lat: 29.6905, lng: -95.407 }], strokeColor: "#2d8065", strokeOpacity: .8, strokeWeight: 5, icons: [{ icon: { path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW, scale: 3 }, offset: "50%", repeat: "90px" }] });
    return () => { traffic.setMap(null); overlays.forEach((o) => o.setMap(null)); flow.setMap(null); };
  }, [selectedMap, overview]);

  const runSimulation = () => {
    simulate.mutate({ name: `${weather} · ${attendance[0].toLocaleString()} attendance`, attendance: attendance[0], startTime, weather, temperatureF: temperature[0], humidity: humidity[0] }, { onSuccess: (result) => setLastOutcome(result.outcome) });
  };
  const trendData = overview?.trends ?? [];
  const nav = [{ label: "Overview", icon: LayoutDashboard }, { label: "Scenario Lab", icon: Activity }, { label: "Risk Monitor", icon: ShieldAlert }, { label: "Event History", icon: History }];


  return <div className="min-h-screen bg-[#f5f8f5] text-[#17322b]">
    <aside className={cn("fixed inset-y-0 left-0 z-40 flex w-[260px] flex-col border-r border-[#e4ece6] bg-[#fbfdfb] px-5 py-6 transition-transform lg:translate-x-0", mobileOpen ? "translate-x-0" : "-translate-x-full")}>
      <div className="flex items-center justify-between px-2"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#183b31] text-white shadow-lg shadow-[#183b31]/20"><Activity className="h-5 w-5" /></div><div><p className="font-display text-lg font-semibold leading-none">ResiliCity</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.2em] text-[#799188]">Houston / 2026</p></div></div><button className="lg:hidden" onClick={() => setMobileOpen(false)}><X className="h-5 w-5" /></button></div>
      <div className="mt-12"><p className="px-3 text-[10px] font-bold uppercase tracking-[.2em] text-[#9aaaA2]">Workspace</p><nav className="mt-3 space-y-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobileOpen(false); }} className={cn("flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-medium transition", active === label ? "bg-[#e3f1e8] text-[#1b654c]" : "text-[#71847b] hover:bg-[#f0f5f1] hover:text-[#31584a]")}><Icon className="h-4 w-4" />{label}{label === "Risk Monitor" && <span className="ml-auto h-2 w-2 rounded-full bg-[#df3d38]" />}</button>)}</nav></div>
      <div className="mt-auto rounded-2xl bg-[#edf5ef] p-4"><div className="flex items-center gap-2 text-xs font-bold text-[#27724f]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#23a455]" />Data systems operational</div><p className="mt-2 text-xs leading-relaxed text-[#6f877b]">Houston event intelligence is ready for planning.</p></div>
      <div className="mt-4 flex items-center gap-3 border-t border-[#e4ece6] px-2 pt-4"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#dcebe3] text-xs font-bold text-[#2d6b53]">G</div><div className="min-w-0"><p className="truncate text-xs font-bold">Guest planner</p><p className="truncate text-[11px] text-[#84948d]">Public workspace</p></div></div>
    </aside>
    <main className="min-h-screen lg:pl-[260px]"><header className="sticky top-0 z-30 flex h-[78px] items-center justify-between border-b border-[#e4ece6]/80 bg-[#f5f8f5]/90 px-5 backdrop-blur-xl sm:px-8"><div className="flex items-center gap-3"><button className="rounded-lg p-2 hover:bg-white lg:hidden" onClick={() => setMobileOpen(true)}><Menu className="h-5 w-5" /></button><div><p className="text-xs font-semibold text-[#7b8d85]">Event intelligence / {active}</p><h1 className="mt-1 font-display text-xl font-semibold tracking-tight sm:text-2xl">NRG Stadium command center</h1></div></div><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-full border border-[#dbe7de] bg-white px-3 py-2 text-xs font-medium text-[#6b8176] sm:flex"><MapPin className="h-3.5 w-3.5 text-[#2d8065]" />Houston, Texas <ChevronRight className="h-3 w-3" /></div><Badge className="border-0 bg-[#e3f1e8] text-[#23704e]">Guest planning mode</Badge></div></header>
      <div className="mx-auto max-w-[1600px] px-5 py-7 sm:px-8 lg:px-10"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-medium text-[#789086]">Tuesday, June 16, 2026 · Match-day planning window</p><div className="mt-2 flex items-center gap-3"><h2 className="font-display text-3xl font-semibold tracking-tight sm:text-4xl">Operational outlook</h2><span className="rounded-full border border-[#f1d36f] bg-[#fff5ca] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-[#896800]">Elevated risk</span></div></div><p className="max-w-sm text-sm leading-relaxed text-[#71847b]">A live decision-support layer for safer, cooler, lower-carbon arrivals around the stadium.</p></div>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Crowd density" value={metrics.crowdDensity} suffix="%" icon={Users} detail="Pedestrian load around stadium bowl" tone={metrics.crowdRisk as any} /><MetricCard label="Heat index" value={metrics.heatIndex} suffix="°F" icon={Thermometer} detail="Peak feels-like temperature estimate" tone={metrics.heatRisk as any} /><MetricCard label="Traffic congestion" value={metrics.trafficCongestion} suffix="%" icon={CarFront} detail="Arrival network saturation" tone={metrics.trafficRisk as any} /><MetricCard label="Overall risk" value={metrics.riskLevel.toUpperCase()} icon={ShieldAlert} detail="Composite operational readiness" tone={metrics.riskLevel as any} /></div>
        <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]"><Card className="overflow-hidden border-0 shadow-[0_12px_36px_rgba(31,48,42,.06)]"><CardHeader className="flex flex-row items-center justify-between border-b border-[#edf1ed] px-5 py-4"><div><CardTitle className="font-display text-lg">Live risk map</CardTitle><p className="mt-1 text-xs text-[#81938a]">Traffic layer, risk zones, and pedestrian flow · NRG Stadium</p></div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-[#81938a]"><span className="h-2 w-2 rounded-full bg-[#df3d38]" />High <span className="ml-2 h-2 w-2 rounded-full bg-[#e1ad10]" />Watch</div></CardHeader><CardContent className="p-0"><div className="relative overflow-hidden bg-[#dfeae1]"><div className="pointer-events-none absolute inset-0 z-0 bg-[linear-gradient(118deg,transparent_0_18%,rgba(255,255,255,.72)_18.2%_19%,transparent_19.2%_35%,rgba(255,255,255,.72)_35.2%_36%,transparent_36.2%_65%,rgba(255,255,255,.72)_65.2%_66%,transparent_66.2%),linear-gradient(25deg,transparent_0_28%,rgba(255,255,255,.65)_28.2%_29%,transparent_29.2%_52%,rgba(255,255,255,.65)_52.2%_53%,transparent_53.2%)] opacity-70" />{!selectedMap && <div className="pointer-events-none absolute inset-0 z-20 flex items-center justify-center"><div className="rounded-2xl border border-white/80 bg-white/85 px-4 py-3 text-center shadow-lg backdrop-blur"><p className="text-xs font-bold text-[#284f42]">Initializing Google Maps layer</p><p className="mt-1 text-[11px] text-[#778a81]">Traffic and risk overlays are loading</p></div></div>}<MapView className="relative z-10 h-[410px]" initialCenter={overview?.center} initialZoom={14} onMapReady={setSelectedMap} /><div className="absolute bottom-4 left-4 z-30 rounded-xl border border-white/80 bg-white/90 px-3 py-2 text-[11px] shadow-lg backdrop-blur"><p className="font-bold text-[#284f42]">{selectedMap ? "Map layers active" : "Map layers queued"}</p><p className="mt-1 text-[#778a81]">Traffic + heat exposure + crowd flow</p></div></div></CardContent></Card>
          <Card className="border-0 bg-[#183b31] text-white shadow-[0_12px_36px_rgba(31,48,42,.12)]"><CardHeader className="px-6 pb-3 pt-6"><div className="flex items-center justify-between"><div><CardTitle className="font-display text-lg text-white">Risk monitor</CardTitle><p className="mt-1 text-xs text-[#b5d0c3]">Color-coded operational alerts</p></div><Gauge className="h-5 w-5 text-[#9dd4b7]" /></div></CardHeader><CardContent className="space-y-3 px-6 pb-6">{[{ name: "Heat exposure", level: metrics.heatRisk, score: metrics.heatIndex, icon: Thermometer }, { name: "Traffic congestion", level: metrics.trafficRisk, score: metrics.trafficCongestion, icon: CarFront }, { name: "Crowd safety", level: metrics.crowdRisk, score: metrics.crowdDensity, icon: Users }].map(({ name, level, score, icon: Icon }) => <div key={name} className="rounded-2xl border border-white/10 bg-white/[.07] p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2.5"><Icon className="h-4 w-4 text-[#a8d9bd]" /><span className="text-sm font-medium">{name}</span></div><RiskBadge level={level} /></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className={cn("h-full rounded-full", riskDot[level])} style={{ width: `${Math.min(100, score)}%` }} /></div><p className="mt-2 text-right text-[11px] text-[#a8c6b8]">Signal strength {score}%</p></div>)}<div className="mt-5 flex items-center justify-between rounded-xl bg-[#2d6652] px-4 py-3"><div><p className="text-xs font-bold">Need to test an intervention?</p><p className="mt-1 text-[11px] text-[#b5d0c3]">Open Scenario Lab below</p></div><ArrowUpRight className="h-4 w-4 text-[#a8d9bd]" /></div></CardContent></Card></div>
        <div className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Card className="border-0 shadow-[0_12px_36px_rgba(31,48,42,.06)]"><CardHeader className="flex flex-row items-center justify-between px-6 pb-1 pt-6"><div><CardTitle className="font-display text-lg">Historical event signals</CardTitle><p className="mt-1 text-xs text-[#81938a]">Temperature, attendance, and congestion trend</p></div><Badge variant="outline" className="border-[#dbe7de] text-[#5b776a]">5 windows</Badge></CardHeader><CardContent className="px-3 pb-5 pt-4"><div className="h-[240px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData}><defs><linearGradient id="temp" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#dd8a5b" stopOpacity={.28}/><stop offset="95%" stopColor="#dd8a5b" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#edf1ed" vertical={false}/><XAxis dataKey="event" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#8a9b93" }}/><YAxis yAxisId="signals" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#8a9b93" }}/><YAxis yAxisId="attendance" orientation="right" hide domain={[0, 90000]} /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid #e1ebe3", fontSize: 12 }} /><Area yAxisId="signals" type="monotone" dataKey="temperature" name="Temperature °F" stroke="#dd8a5b" fill="url(#temp)" strokeWidth={2.5}/><Area yAxisId="signals" type="monotone" dataKey="congestion" name="Congestion %" stroke="#2d8065" fill="transparent" strokeWidth={2.5}/><Area yAxisId="attendance" type="monotone" dataKey="attendance" name="Attendance" stroke="#7b8eeb" fill="transparent" strokeWidth={2} strokeDasharray="4 4" /></AreaChart></ResponsiveContainer></div></CardContent></Card>
          <Card className="border-0 shadow-[0_12px_36px_rgba(31,48,42,.06)]"><CardHeader className="px-6 pb-1 pt-6"><CardTitle className="font-display text-lg">Resilience actions</CardTitle><p className="mt-1 text-xs text-[#81938a]">Recommendations from the current model run</p></CardHeader><CardContent className="space-y-3 px-6 pb-6 pt-4">{recommendationList.map((text, i) => <div key={text} className="flex gap-3 rounded-xl border border-[#e4ece6] bg-[#fbfdfb] p-3"><div className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#e3f1e8] text-[#287a55]"><CheckCircle2 className="h-3.5 w-3.5" /></div><p className="text-xs leading-relaxed text-[#587168]">{text}</p></div>)}<div className="mt-2 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#eef8f0] p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-[#779488]">Carbon saved</p><p className="mt-1 text-lg font-semibold text-[#26764f]">{lastOutcome?.carbonSavedTons ?? 14.2} <span className="text-xs font-normal">tons</span></p></div><div className="rounded-xl bg-[#f0f5f1] p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-[#779488]">Travel time</p><p className="mt-1 text-lg font-semibold text-[#26764f]">{lastOutcome?.minutesSaved ?? 18} <span className="text-xs font-normal">min saved</span></p></div></div></CardContent></Card></div>
        <div className="mt-6 grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><Card className="border-0 shadow-[0_12px_36px_rgba(31,48,42,.06)]"><CardHeader className="px-6 pb-2 pt-6"><div className="flex items-center justify-between"><div><CardTitle className="font-display text-lg">Scenario Lab</CardTitle><p className="mt-1 text-xs text-[#81938a]">Run a public match-day simulation</p></div><Activity className="h-5 w-5 text-[#2d8065]" /></div></CardHeader><CardContent className="space-y-5 px-6 pb-6 pt-3"><div><div className="mb-2 flex justify-between"><Label className="text-xs font-semibold text-[#597268]">Attendance</Label><span className="text-sm font-bold text-[#1b5d47]">{attendance[0].toLocaleString()}</span></div><Slider value={attendance} min={20000} max={90000} step={1000} onValueChange={setAttendance} /></div><div><div className="mb-2 flex justify-between"><Label className="text-xs font-semibold text-[#597268]">Temperature</Label><span className="text-sm font-bold text-[#1b5d47]">{temperature[0]}°F</span></div><Slider value={temperature} min={75} max={105} step={1} onValueChange={setTemperature} /></div><div><div className="mb-2 flex justify-between"><Label className="text-xs font-semibold text-[#597268]">Humidity</Label><span className="text-sm font-bold text-[#1b5d47]">{humidity[0]}%</span></div><Slider value={humidity} min={20} max={95} step={1} onValueChange={setHumidity} /></div><div className="grid gap-4 sm:grid-cols-2"><div><Label className="text-xs font-semibold text-[#597268]">Start time</Label><Input type="time" value={startTime} onChange={(e) => setStartTime(e.target.value)} className="mt-2 rounded-xl border-[#dbe7de] bg-[#fbfdfb]" /></div><div><Label className="text-xs font-semibold text-[#597268]">Weather profile</Label><Select value={weather} onValueChange={(v) => setWeather(v as typeof weather)}><SelectTrigger className="mt-2 rounded-xl border-[#dbe7de] bg-[#fbfdfb]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Hot & humid">Hot & humid</SelectItem><SelectItem value="Warm and clear">Warm and clear</SelectItem><SelectItem value="Storm watch">Storm watch</SelectItem><SelectItem value="Mild evening">Mild evening</SelectItem></SelectContent></Select></div></div><Button onClick={runSimulation} disabled={simulate.isPending} className="w-full rounded-xl bg-[#183b31] py-5 text-sm hover:bg-[#275d4d]">{simulate.isPending ? "Running simulation…" : "Run and save simulation"}<ArrowUpRight className="ml-2 h-4 w-4" /></Button><p className="text-center text-[11px] text-[#81938a]">Runs are available directly in this public planning workspace.</p></CardContent></Card>
          <Card className="border-0 shadow-[0_12px_36px_rgba(31,48,42,.06)]"><CardHeader className="flex flex-row items-center justify-between px-6 pb-2 pt-6"><div><CardTitle className="font-display text-lg">Scenario history</CardTitle><p className="mt-1 text-xs text-[#81938a]">Saved simulation runs and outcome summaries</p></div><History className="h-5 w-5 text-[#2d8065]" /></CardHeader><CardContent className="px-6 pb-6 pt-3">{history.length === 0 ? <div className="flex min-h-[210px] items-center justify-center text-sm text-[#81938a]">Run your first scenario to populate this history.</div> : <div className="space-y-2">{history.slice(0, 5).map((item) => <button key={item.id} onClick={() => setCompareIds((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : current.length < 3 ? [...current, item.id] : current)} className={cn("flex w-full items-center justify-between rounded-xl border p-3 text-left transition", compareIds.includes(item.id) ? "border-[#6eb48b] bg-[#edf8f0]" : "border-[#e4ece6] hover:bg-[#fbfdfb]")}><div className="min-w-0"><p className="truncate text-sm font-semibold">{item.name}</p><p className="mt-1 text-[11px] text-[#81938a]">{new Date(item.createdAt).toLocaleString()} · {item.attendance.toLocaleString()} attendees</p></div><div className="flex items-center gap-3"><RiskBadge level={item.riskLevel} /><span className="hidden text-xs font-semibold text-[#27724f] sm:inline">{item.carbonSavedTons}t CO₂</span></div></button>)}{comparison.length > 0 && <div className="mt-4 rounded-2xl bg-[#183b31] p-4 text-white"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider">Compare selected runs</p><span className="text-[10px] text-[#b5d0c3]">{comparison.length} selected</span></div><div className="mt-3 grid gap-2 sm:grid-cols-3">{comparison.map((item) => <div key={item.id} className="rounded-xl bg-white/10 p-3"><p className="truncate text-[11px] font-semibold">{item.name}</p><p className="mt-2 text-lg font-semibold">{item.riskLevel.toUpperCase()}</p><p className="mt-1 text-[10px] text-[#b5d0c3]">{item.trafficCongestion}% congestion · {item.heatIndex}°F</p></div>)}</div></div>}</div>}</CardContent></Card></div>
      </div>
    </main>
  </div>;
}
